import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AdminService } from '../../core/services/admin.service';
import { DrawService } from '../../core/services/draw.service';
import { User } from '../../core/models/user.model';
import { Draw, RoundDigit } from '../../core/models/draw.model';

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin.component.html'
})
export class AdminComponent implements OnInit {
  users: User[] = [];
  draws: Draw[] = [];
  selectedDrawId: number | null = null;
  digits: RoundDigit[] = [];
  loadingUsers = false;
  loadingDraws = false;
  actionLoading = false;
  alert: { type: 'success' | 'danger' | 'info'; message: string } | null = null;

  constructor(
    private readonly adminService: AdminService,
    private readonly drawService: DrawService
  ) {}

  ngOnInit(): void {
    this.loadUsers();
    this.loadDraws();
  }

  loadUsers(): void {
    this.loadingUsers = true;
    this.adminService.findAllUsers().subscribe(users => {
      this.loadingUsers = false;
      this.users = users;
    });
  }

  loadDraws(): void {
    this.loadingDraws = true;
    this.drawService.findAllDraws().subscribe(draws => {
      this.loadingDraws = false;
      this.draws = [...draws].sort((a, b) => b.drawId - a.drawId);
      this.selectedDrawId = this.draws[0]?.drawId ?? null;
    });
  }

  generateDraw(): void {
    this.actionLoading = true;
    this.alert = null;

    this.drawService.autoGenerateDraw().subscribe({
      next: draw => {
        this.actionLoading = false;
        this.alert = { type: 'success', message: `Sorteio #${draw.drawId} criado.` };
        this.loadDraws();
      },
      error: () => {
        this.actionLoading = false;
        this.alert = { type: 'danger', message: 'Não foi possível criar o sorteio.' };
      }
    });
  }

  startSelectedDraw(): void {
    if (!this.selectedDrawId) {
      this.alert = { type: 'danger', message: 'Selecione um sorteio.' };
      return;
    }

    this.actionLoading = true;
    this.alert = null;

    this.drawService.startDraw(this.selectedDrawId).subscribe({
      next: message => {
        this.actionLoading = false;
        this.alert = { type: 'success', message: message || 'Sorteio finalizado.' };
        this.loadDraws();
        this.loadDigits();
      },
      error: error => {
        this.actionLoading = false;
        this.alert = { type: 'danger', message: error?.error || 'Não foi possível finalizar o sorteio.' };
      }
    });
  }

  loadDigits(): void {
    if (!this.selectedDrawId) {
      this.digits = [];
      return;
    }

    this.drawService.findRoundDigitsByDrawId(this.selectedDrawId).subscribe(digits => this.digits = digits);
  }

  positionLabel(position?: string | null): string {
    const labels: Record<string, string> = {
      HEAD: 'Cabeça',
      SECOND: '2ª rodada',
      THIRD: '3ª rodada',
      FOURTH: '4ª rodada',
      FIFTH: '5ª rodada'
    };

    return position ? labels[position] || position : '-';
  }

  trackUser(_: number, user: User): number {
    return user.userId;
  }

  trackDraw(_: number, draw: Draw): number {
    return draw.drawId;
  }
}
