import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { catchError, map, Observable, of } from 'rxjs';
import { environment } from '../../../environments/environment';
import { Draw, RoundDigit } from '../models/draw.model';

@Injectable({ providedIn: 'root' })
export class DrawService {
  private readonly apiUrl = `${environment.apiUrl}/app/admin/draw`;
  private readonly activeDrawKey = 'fullBicho.activeDraw';

  constructor(private readonly http: HttpClient) {}

  autoGenerateDraw(): Observable<Draw> {
    return this.http.post<Draw>(`${this.apiUrl}/autoGenerateDraw`, {});
  }

  generateDraw(): Observable<Draw> {
    return this.http.post<Draw>(`${this.apiUrl}/generateDraw`, {});
  }

  startDraw(drawId: number): Observable<string> {
    const params = new HttpParams().set('drawId', drawId);
    return this.http.post(`${this.apiUrl}/startDraw`, null, {
      params,
      responseType: 'text'
    });
  }

  findAllDraws(): Observable<Draw[]> {
    return this.http.get<Draw[]>(`${this.apiUrl}/findAllDraws`).pipe(
      map(draws => draws ?? []),
      catchError(() => of([]))
    );
  }

  findRoundDigitsByDrawId(drawId: number): Observable<RoundDigit[]> {
    const params = new HttpParams().set('drawId', drawId);
    return this.http.get<RoundDigit[]>(`${this.apiUrl}/findRoundDigitsByDrawId`, { params }).pipe(
      map(digits => digits ?? []),
      catchError(() => of([]))
    );
  }

  saveActiveDraw(draw: Draw): void {
    localStorage.setItem(this.activeDrawKey, JSON.stringify(draw));
  }

  readActiveDraw(): Draw | null {
    const stored = localStorage.getItem(this.activeDrawKey);

    if (!stored) {
      return null;
    }

    try {
      return JSON.parse(stored) as Draw;
    } catch {
      this.clearActiveDraw();
      return null;
    }
  }

  clearActiveDraw(): void {
    localStorage.removeItem(this.activeDrawKey);
  }
}
