package FullBicho.app.controller;

import FullBicho.app.dto.DrawRequestDTO;
import FullBicho.app.entity.Draw;
import FullBicho.app.entity.User;
import FullBicho.app.service.DrawService;
import FullBicho.app.service.UserService;
import ch.qos.logback.core.spi.LifeCycle;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cglib.core.Local;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;

@RestController
@RequestMapping("/app/admin/draw")
public class DrawController {

    @Autowired
    private DrawService drawService;


    @PostMapping("/autoGenerateDraw")
    public ResponseEntity<Draw> generateDraw(@RequestBody DrawRequestDTO drawDTO){
        try{
            Draw draw = drawService.generateDraw(drawDTO);
            return new ResponseEntity<>(draw, HttpStatus.OK);
        }
        catch (Exception e){
            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
        }

    }

    @GetMapping("/autoGenerateDraw")
    public ResponseEntity<Draw> autoGenerateDraw(){
        try{
            Draw draw = drawService.autoGenerateDraw();
            return new ResponseEntity<>(draw, HttpStatus.OK);
        }
        catch (Exception e){
            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
        }

    }

    @GetMapping("/startDraw/{id}")
    public ResponseEntity<String> startDraw(@PathVariable Long  id){
        try{
            String message = drawService.startDraw(id);
            return new ResponseEntity<>(message, HttpStatus.OK);
        }
        catch (Exception e){
            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
        }

    }


}
