package FullBicho.app.service;

import FullBicho.app.dto.DrawRequestDTO;
import FullBicho.app.entity.Bet;
import FullBicho.app.entity.Draw;
import FullBicho.app.entity.RoundDigit;
import FullBicho.app.entity.User;
import FullBicho.app.repository.BetRepository;
import FullBicho.app.repository.DrawRepository;
import FullBicho.app.repository.RoundDigitRepository;
import FullBicho.app.repository.UserRepository;
import FullBicho.app.util.BetStatus;
import FullBicho.app.util.DrawStatus;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Service
public class DrawService {


    @Autowired
    private DrawRepository drawRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private RoundDigitService  roundDigitService;
    @Autowired
    private RoundDigitRepository   roundDigitRepository;
    @Autowired
    private BetRepository betRepository;
    @Autowired
    private BetProcessService betProcessService;


    //TODO - PARA GERAR UM DRAW COM PARÂMETROS ESPECÍFICOS
    @Transactional
    public Draw generateDraw(DrawRequestDTO drawDTO) {


        Draw nextDraw = new Draw();
        LocalDateTime drawTime = LocalDateTime.now();

        nextDraw.setDrawTime(drawTime);
        nextDraw.setCreatedAt(LocalDateTime.now());
        nextDraw.setStatus(DrawStatus.OPEN);

        return drawRepository.save(nextDraw);
    }

    @Transactional
    public Draw autoGenerateDraw() {

        Draw nextDraw = new Draw();
        LocalDateTime drawTime = LocalDateTime.now();

        nextDraw.setDrawTime(drawTime);
        nextDraw.setCreatedAt(LocalDateTime.now());
        nextDraw.setStatus(DrawStatus.OPEN);

        return drawRepository.save(nextDraw);
    }




    @Transactional
    public String startDraw(Long currentDrow_id){

        //busca draw-----------------
        Draw draw = drawRepository.findById(currentDrow_id).orElseThrow(() -> new RuntimeException("Sorteio Não Encontrado!"));

        //validar se OPEN------------
        if (!draw.isOpen()) {throw new IllegalStateException("Sorteio Já Encerrado!");}


        //GERAR DIGITS----------
        roundDigitService.generateForDraw(draw);
        System.out.println("vals gerados");

        //Buscar Digits ----------------
        List<RoundDigit> results = roundDigitRepository.findByDraw_drawId(currentDrow_id);

        //Buscar bets ----------------
        List<Bet> bets = betRepository.findByDraw_drawIdAndStatus(currentDrow_id, BetStatus.PENDING);

        //PROCESSAR BETS ----------------
        betProcessService.processBets(bets, results);

        draw.setStatus(DrawStatus.CLOSED);
        drawRepository.save(draw);


        return  "DRAW INICIADO E FINALIZADO!!!";
    }



}
///  Ajsutar para saber se o digit bate e qual a posição0
