package FullBicho.app.service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import FullBicho.app.dto.DrawRequestDTO;
import FullBicho.app.entity.Bet;
import FullBicho.app.entity.Draw;
import FullBicho.app.entity.RoundDigit;
import FullBicho.app.repository.BetRepository;
import FullBicho.app.repository.DrawRepository;
import FullBicho.app.repository.RoundDigitRepository;
import FullBicho.app.repository.UserRepository;
import FullBicho.app.util.items.BetStatus;
import FullBicho.app.util.items.DrawStatus;
import jakarta.transaction.Transactional;

@Service
public class DrawService {


    @Autowired
    private DrawRepository drawRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private RoundDigitService  roundDigitService;
    @Autowired
    private RoundDigitRepository   roundDigitRepository;
    @Autowired
    private BetRepository betRepository;
    @Autowired
    private BetProcessService betProcessService;


    //TODO - PARA GERAR UM DRAW COM PARÂMETROS ESPECÍFICOS
    @Transactional
    public Draw generateDraw(DrawRequestDTO drawDTO) {


        Draw nextDraw = new Draw();
        LocalDateTime drawTime = LocalDateTime.now();

        nextDraw.setDrawTime(drawTime);
        nextDraw.setCreatedAt(LocalDateTime.now());
        nextDraw.setStatus(DrawStatus.OPEN);

        return drawRepository.save(nextDraw);
    }

    @Transactional
    public Draw autoGenerateDraw() {

        Draw nextDraw = new Draw();
        LocalDateTime drawTime = LocalDateTime.now();

        nextDraw.setDrawTime(drawTime);
        nextDraw.setCreatedAt(LocalDateTime.now());
        nextDraw.setStatus(DrawStatus.OPEN);

        return drawRepository.save(nextDraw);
    }




    @Transactional
    public String startDraw(Long currentDrow_id){

            //busca draw-----------------
            Optional<Draw> tempDraw = drawRepository.findById(currentDrow_id);

            if (tempDraw.isEmpty()) {
                throw new RuntimeException("Sorteio não Encontrado!");
            }

            Draw  draw = tempDraw.get();


            //validar se OPEN------------
            if (!draw.isOpen()) {
                throw new IllegalStateException("Sorteio já Encerrado!");
            }


            //GERAR DIGITS----------
            try {
                roundDigitService.generateForDraw(draw);

            }
            catch (Exception e){
                throw new RuntimeException(e.getMessage());
            }


            //Buscar Digits ----------------

            List<RoundDigit> results = roundDigitRepository.findByDraw_drawId(currentDrow_id);

            if (results.isEmpty()) {
                throw new RuntimeException("Erro ao gerar rodadas!!!");
            }

            //Buscar bets ----------------
            List<Bet> bets = betRepository.findByDraw_drawIdAndStatus(currentDrow_id, BetStatus.PENDING);

            if  (bets.isEmpty()) {
                throw new RuntimeException("Nenhuma bet alocada!!!");
            }
            //PROCESSAR BETS ----------------

            try {
                betProcessService.processBets(bets, results);
            }
            catch (Exception e){
                throw new RuntimeException(e.getMessage());
            }

            draw.setStatus(DrawStatus.CLOSED);
            drawRepository.save(draw);


            return  "Número gerado e sorteio fechado!!!";

    }
    public List<Draw> findAllDraws() {
        try {
            return drawRepository.findAll();
        }
        catch (Exception e) {
            throw new RuntimeException(e.getMessage());
        }
    }

    public Draw findDrawById(Long drawId) {
        return drawRepository.findById(drawId)
                .orElseThrow(() -> new RuntimeException("Sorteio não encontrado!"));
    }

    public List<RoundDigit> findRoundDigitsByDrawId(Long drawId) {
        return roundDigitRepository.findByDraw_drawId(drawId);
    }


}
///  Ajsutar para saber se o digit bate e qual a posição0
